import type { Story, Setup } from '../types'

// Build a DALL-E 3 prompt from story metadata — no character descriptions,
// focused on mood and setting so it's safe and doesn't conflict with the
// identity-free story approach.
function buildDallEPrompt(story: Story): string {
  const mood = story.destination
    ? `evoking "${story.destination}"`
    : story.mode === 'teen' ? 'wonder and quiet discovery' : 'warmth and gentle resolution'
  return (
    `Soft, dreamy watercolor illustration for a teen bedtime story titled "${story.title}", ` +
    `${mood}. A quiet atmospheric scene with no people, no faces, no text. ` +
    `Warm muted palette, gentle lamplight or moonlight. Painterly book illustration style.`
  )
}

// Ask Claude Haiku to generate a minimal SVG — abstract shapes only,
// no people, under ~1 KB so it stores cleanly as a data URI.
function buildSVGPrompt(story: Story): string {
  return (
    `Generate a minimal SVG illustration (viewBox="0 0 400 240") for a bedtime story ` +
    `titled "${story.title}". Use 5–8 soft abstract shapes suggesting mood and setting. ` +
    `No people, no faces, no text. Warm muted colours. ` +
    `Output ONLY the raw <svg> element — no explanation, no code fences.`
  )
}

// Convert a remote URL to a persistent base64 data URI so it survives
// after the DALL-E URL expires (1 hour).
async function urlToDataURI(url: string): Promise<string> {
  const res = await fetch(url)
  const blob = await res.blob()
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result as string)
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

async function generateWithDallE(story: Story, apiKey: string): Promise<string | null> {
  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'dall-e-3',
      prompt: buildDallEPrompt(story),
      n: 1,
      size: '1024x1024',
      quality: 'standard',
    }),
  })
  if (!res.ok) return null
  const data = await res.json() as { data: Array<{ url: string }> }
  const url = data.data?.[0]?.url
  if (!url) return null
  // Download and encode so the illustration persists beyond the 1-hour URL TTL
  return urlToDataURI(url)
}

async function generateWithClaudeSVG(story: Story, apiKey: string): Promise<string | null> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
      'anthropic-dangerous-direct-browser-calls': 'true',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [{ role: 'user', content: buildSVGPrompt(story) }],
    }),
  })
  if (!res.ok) return null
  const data = await res.json() as { content: Array<{ text: string }> }
  const raw = data.content?.[0]?.text ?? ''
  const match = raw.match(/<svg[\s\S]*?<\/svg>/i)
  if (!match) return null
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(match[0])}`
}

// Main entry point. Returns a persistent data URI or null.
// Local/Gemma → null (no image capability).
// OpenAI → DALL-E 3 (downloaded to base64).
// Claude → SVG generated by Haiku.
export async function generateIllustration(story: Story, setup: Setup): Promise<string | null> {
  if (setup.useLocal) return null
  try {
    if (setup.provider === 'openai' && setup.apiKey) return await generateWithDallE(story, setup.apiKey)
    if (setup.provider === 'claude' && setup.apiKey) return await generateWithClaudeSVG(story, setup.apiKey)
  } catch {
    // Illustration is non-critical — degrade gracefully
  }
  return null
}
